document.write( '<footer class=\"with-sider\">\n' );
document.write( '                <div class=\"container\">\n' );
document.write( '                    <div class=\"inner-wrapper ai-fs jc-sb\">\n' );
document.write( '                        <div class=\"footer-item\">\n' );
document.write( '                            <h3 class=\"footer-item-title\">資助 PCUI</h3>\n' );
document.write( '                            <div class=\"footer-item-txt\">\n' );
document.write( '                                免費開發source需要龐大的心力以及時間，\n' );
document.write( '                                雖然只是一個間單的功能，但如果有幫助到\n' );
document.write( '                                您，還請不吝嗇給予一些支持吧！\n' );
document.write( '                            </div>\n' );
document.write( '                            <a href=\"http://\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"primary-btn\"><span>贊助我</span></a>\n' );
document.write( '                        </div>\n' );
document.write( '                        <div class=\"footer-item\">\n' );
document.write( '                            <h3 class=\"footer-item-title\">加入我們</h3>\n' );
document.write( '                            <div class=\"footer-item-txt\">\n' );
document.write( '                                免費開發source需要龐大的心力以及時間，如果你有興趣加入我們，快來吧！\n' );
document.write( '                            </div>\n' );
document.write( '                            <a href=\"http://\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"primary-btn\"><span>加入我們</span></a>\n' );
document.write( '                        </div>\n' );
document.write( '                        <div class=\"footer-item\">\n' );
document.write( '                            <h3 class=\"footer-item-title\">聯絡我</h3>\n' );
document.write( '                            <div class=\"footer-item-txt\">\n' );
document.write( '                                任何問題都可以提出，請聯絡我。\n' );
document.write( '                            </div>\n' );
document.write( '                            <a href=\"http://\" target=\"_blank\" rel=\"noopener noreferrer\" class=\"primary-btn\"><span>聯絡我</span></a>\n' );
document.write( '                        </div>\n' );
document.write( '                    </div>\n' );
document.write( '                </div>\n' );
document.write( '            </footer>' );
