document.write( '<nav id="navbar" class=\"side-nav\">\n' );
document.write( '                    <div class=\"nav-wrapper\">\n' );
document.write( '                        <div class=\"nav-header\">\n' );
document.write( '                            <div class=\"inner-wrapper\">\n' );
document.write( '                                <a href=\"index.html\" class=\"nav-logo-thumb\">\n' );
document.write( '                                    <img src=\"https://cdn.jsdelivr.net/gh/zqartwork/zqartworkImage/pcui/logo.svg\" alt=\"\" class=\"logo\">\n' );
document.write( '                                </a>\n' );
document.write( '                                <div class=\"nav-logo-title\">Project of Cloud UI</div>\n' );
document.write( '                                <div class=\"search-bar-wrapper\">\n' );
document.write( '                                    <input type=\"text\" class=\"search-input shrinking-placeholder\">\n' );
document.write( '                                    <label class=\"search-title\">Search</label>\n' );
document.write( '                                    <i class=\"fas fa-search search-icon\"></i>\n' );
document.write( '                                </div>\n' );
document.write( '                            </div>\n' );
document.write( '                        </div>\n' );
document.write( '                        <div class=\"nav-body\">\n' );
document.write( '                            <div class=\"nav-item-wrapper\">\n' );
document.write( '                                <a href=\"about.html\" class=\"nav-item\"><span>About</span></a>\n' );
document.write( '                                <a href=\"getting-start.html\" class=\"nav-item\"><span>Getting Start</span></a>\n' );
document.write( '                                <div class=\"nav-item collapsible-opener\" sw=\"#css\"><span>CSS</span></div>\n' );
document.write( '                                <div id=\"css\" class=\"collapsible-list\">\n' );
document.write( '                                    <a href=\"grid.html\" class=\"nav-item\"><span>Grid</span></a>\n' );
document.write( '                                    <a href=\"helpers.html\" class=\"nav-item\"><span>Helpers</span></a>\n' );
document.write( '                                    <a href=\"media.html\" class=\"nav-item\"><span>Media</span></a>\n' );
document.write( '                                    <a href=\"animation.html\" class=\"nav-item\"><span>Animation</span></a>\n' );
document.write( '                                    <a href=\"shadow.html\" class=\"nav-item\"><span>Shadow</span></a>\n' );
document.write( '                                    <a href=\"transition.html\" class=\"nav-item\"><span>Transition</span></a>\n' );
document.write( '                                    <a href=\"typography.html\" class=\"nav-item\"><span>Typography</span></a>\n' );
document.write( '                                </div>\n' );
document.write( '                                <div class=\"nav-item collapsible-opener\" sw=\"#components\"><span>Components</span></div>\n' );
document.write( '                                <div id=\"components\" class=\"collapsible-list\">\n' );
document.write( '                                    <a href=\"badges.html\" class=\"nav-item\"><span>Badges</span></a>\n' );
document.write( '                                    <a href=\"buttons.html\" class=\"nav-item\"><span>Buttons</span></a>\n' );
document.write( '                                    <a href=\"breadcrumbs.html\" class=\"nav-item\"><span>Breadcrumbs</span></a>\n' );
document.write( '                                    <a href=\"cards.html\" class=\"nav-item\"><span>Cards</span></a>\n' );
document.write( '                                    <a href=\"collections.html\" class=\"nav-item\"><span>Collections</span></a>\n' );
document.write( '                                    <a href=\"floating-action-buttons.html\" class=\"nav-item\"><span>Floating Action Buttons</span></a>\n' );
document.write( '                                    <a href=\"footer,html\" class=\"nav-item\"><span>Footer</span></a>\n' );
document.write( '                                    <a href=\"icons.html\" class=\"nav-item\"><span>Icons</span></a>\n' );
document.write( '                                    <a href=\"navbar.html\" class=\"nav-item\"><span>Navbar</span></a>\n' );
document.write( '                                    <a href=\"pagination.html\" class=\"nav-item\"><span>Pagination</span></a>\n' );
document.write( '                                    <a href=\"preloader.html\" class=\"nav-item\"><span>Preloader</span></a>\n' );
document.write( '                                </div>\n' );
document.write( '                                <div class=\"nav-item collapsible-opener\" sw=\"#js\"><span>Javascript</span></div>\n' );
document.write( '                                <div id=\"js\" class=\"collapsible-list\">\n' );
document.write( '                                    <a href=\"carousel.html\" class=\"nav-item\"><span>Carousel</span></a>\n' );
document.write( '                                    <a href=\"collapsible.html\" class=\"nav-item\"><span>Collapsible</span></a>\n' );
document.write( '                                    <a href=\"remote-control.html\" class=\"nav-item\"><span>Remote Control</span></a>\n' );
document.write( '                                    <a href=\"media-box.html\" class=\"nav-item\"><span>Media Box</span></a>\n' );
document.write( '                                    <a href=\"modals.html\" class=\"nav-item\"><span>Modals</span></a>\n' );
document.write( '                                    <a href=\"parallax.html\" class=\"nav-item\"><span>Parallax</span></a>\n' );
document.write( '                                    <a href=\"push-pin.html\" class=\"nav-item\"><span>Push Pin</span></a>\n' );
document.write( '                                    <a href=\"scrollspy.html\" class=\"nav-item\"><span>Scrollspy</span></a>\n' );
document.write( '                                    <a href=\"sidenav.html\" class=\"nav-item\"><span>Sidenav</span></a>\n' );
document.write( '                                    <a href=\"tabs.html\" class=\"nav-item\"><span>Tabs</span></a>\n' );
document.write( '                                    <a href=\"toasts.html\" class=\"nav-item\"><span>Toasts</span></a>\n' );
document.write( '                                    <a href=\"tooltips.html\" class=\"nav-item\"><span>Tooltips</span></a>\n' );
document.write( '                                    <a href=\"btn-active-animation.html\" class=\"nav-item\"><span>BTN Active Animation</span></a>\n' );
document.write( '                                </div>\n' );
document.write( '                                <div class=\"nav-item collapsible-opener\" sw=\"#form\"><span>Form</span></div>\n' );
document.write( '                                <div id=\"form\" class=\"collapsible-list\">\n' );
document.write( '                                    <a href=\"dropdown.html\" class=\"nav-item\"><span>Dropdown</span></a>\n' );
document.write( '                                    <a href=\"shrinking-inputs.html\" class=\"nav-item\"><span>Shrinking Inputs</span></a>\n' );
document.write( '                                    <a href=\"checkbox.html\" class=\"nav-item\"><span>Checkbox</span></a>\n' );
document.write( '                                    <a href=\"tags.html\" class=\"nav-item\"><span>Tags</span></a>\n' );
document.write( '                                    <a href=\"datepicker.html\" class=\"nav-item\"><span>Datepicker</span></a>\n' );
document.write( '                                    <a href=\"radio.html\" class=\"nav-item\"><span>Radio</span></a>\n' );
document.write( '                                    <a href=\"range.html\" class=\"nav-item\"><span>Range</span></a>\n' );
document.write( '                                    <a href=\"select.html\" class=\"nav-item\"><span>Select</span></a>\n' );
document.write( '                                    <a href=\"switches.html\" class=\"nav-item\"><span>Switches</span></a>\n' );
document.write( '                                    <a href=\"uploader.html\" class=\"nav-item\"><span>Uploader</span></a>\n' );
document.write( '                                </div>\n' );
document.write( '                            </div>\n' );
document.write( '                        </div>\n' );
document.write( '                        <div class=\"nav-footer\"></div>\n' );
document.write( '                    </div>\n' );
document.write( '                </nav>' );
document.write( '<div class=\"side-nav-closer side-nav-mask\"></div>\n' );
document.write( '            <a href=\"#!\" class=\"ham side-nav-opener\">\n' );
document.write( '                <img src=\"https://cdn.jsdelivr.net/gh/zqartwork/zqartworkImage/img/PCUI/ham.png\" alt=\"\">\n' );
document.write( '            </a>' );

