document.write( '<nav id=”navbar” class=\"side-nav\">\n' );
document.write( '                    <div class=\"nav-wrapper\">\n' );
document.write( '                        <div class=\"nav-header\">\n' );
document.write( '                            <div class=\"inner-wrapper\">\n' );
document.write( '                                <a href=\"index.html\" class=\"nav-logo-thumb\">\n' );
document.write( '                                    <img src=\"https://cdn.jsdelivr.net/gh/zqartwork/zqartworkImage/pcui/logo.svg\" alt=\"\" class=\"logo\">\n' );
document.write( '                                </a>\n' );
document.write( '                                <div class=\"nav-logo-title\">Project of Cloud UI</div>\n' );
document.write( '                                <div class=\"search-bar-wrapper\">\n' );
document.write( '                                    <input type=\"text\" class=\"search-input shrinking-placeholder\">\n' );
document.write( '                                    <label class=\"search-title\">Search</label>\n' );
document.write( '                                    <i class=\"fas fa-search search-icon\"></i>\n' );
document.write( '                                </div>\n' );
document.write( '                            </div>\n' );
document.write( '                        </div>\n' );
document.write( '                        <div class=\"nav-body\">\n' );
document.write( '                            <div class=\"nav-item-wrapper\">\n' );
document.write( '                                <a href=\"about.html\" class=\"nav-item\"><span>About</span></a>\n' );
document.write( '                                <a href=\"getting-start.html\" class=\"nav-item\"><span>Getting Start</span></a>\n' );
document.write( '                                <div class=\"nav-item collapsible-opener\" sw=\"#css\"><span>CSS</span></div>\n' );
document.write( '                                <div id=\"css\" class=\"collapsible-list\">\n' );
document.write( '                                    <a href=\"pcss/grid.html\" class=\"nav-item\"><span>Grid</span></a>\n' );
document.write( '                                    <a href=\"pcss/helper.html\" class=\"nav-item\"><span>Helpers</span></a>\n' );
document.write( '                                    <a href=\"pcss/media.html\" class=\"nav-item\"><span>Media</span></a>\n' );
document.write( '                                    <a href=\"pcss/animation.html\" class=\"nav-item\"><span>Animation</span></a>\n' );
document.write( '                                    <a href=\"pcss/scss.html\" class=\"nav-item\"><span>Scss</span></a>\n' );
document.write( '                                    <a href=\"pcss/shadow.html\" class=\"nav-item\"><span>Shadow</span></a>\n' );
document.write( '                                    <a href=\"pcss/table.html\" class=\"nav-item\"><span>Table</span></a>\n' );
document.write( '                                    <a href=\"pcss/transition.html\" class=\"nav-item\"><span>Transition</span></a>\n' );
document.write( '                                    <a href=\"pcss/typography.html\" class=\"nav-item\"><span>Typography</span></a>\n' );
document.write( '                                </div>\n' );
document.write( '                                <div class=\"nav-item collapsible-opener\" sw=\"#components\"><span>Components</span></div>\n' );
document.write( '                                <div id=\"components\" class=\"collapsible-list\">\n' );
document.write( '                                    <a href=\"comp/badges.html\" class=\"nav-item\"><span>Badges</span></a>\n' );
document.write( '                                    <a href=\"comp/buttons.html\" class=\"nav-item\"><span>Buttons</span></a>\n' );
document.write( '                                    <a href=\"comp/breadcrumbs.html\" class=\"nav-item\"><span>Breadcrumbs</span></a>\n' );
document.write( '                                    <a href=\"comp/cards.html\" class=\"nav-item\"><span>Cards</span></a>\n' );
document.write( '                                    <a href=\"comp/collections.html\" class=\"nav-item\"><span>Collections</span></a>\n' );
document.write( '                                    <a href=\"comp/floating-action-buttons.html\" class=\"nav-item\"><span>Floating Action Buttons</span></a>\n' );
document.write( '                                    <a href=\"comp/footer,html\" class=\"nav-item\"><span>Footer</span></a>\n' );
document.write( '                                    <a href=\"comp/icons.html\" class=\"nav-item\"><span>Icons</span></a>\n' );
document.write( '                                    <a href=\"comp/navbar.html\" class=\"nav-item\"><span>Navbar</span></a>\n' );
document.write( '                                    <a href=\"comp/pagination.html\" class=\"nav-item\"><span>Pagination</span></a>\n' );
document.write( '                                    <a href=\"comp/preloader.html\" class=\"nav-item\"><span>Preloader</span></a>\n' );
document.write( '                                </div>\n' );
document.write( '                                <div class=\"nav-item collapsible-opener\" sw=\"#js\"><span>Javascript</span></div>\n' );
document.write( '                                <div id=\"js\" class=\"collapsible-list\">\n' );
document.write( '                                    <a href=\"pjs/carousel.html\" class=\"nav-item\"><span>Carousel</span></a>\n' );
document.write( '                                    <a href=\"pjs/collapsible.html\" class=\"nav-item\"><span>Collapsible</span></a>\n' );
document.write( '                                    <a href=\"pjs/remote-control.html\" class=\"nav-item\"><span>Remote Control</span></a>\n' );
document.write( '                                    <a href=\"pjs/media-box.html\" class=\"nav-item\"><span>Media Box</span></a>\n' );
document.write( '                                    <a href=\"pjs/modals.html\" class=\"nav-item\"><span>Modals</span></a>\n' );
document.write( '                                    <a href=\"pjs/parallax.html\" class=\"nav-item\"><span>Parallax</span></a>\n' );
document.write( '                                    <a href=\"pjs/push-pin.html\" class=\"nav-item\"><span>Push Pin</span></a>\n' );
document.write( '                                    <a href=\"pjs/scrollspy.html\" class=\"nav-item\"><span>Scrollspy</span></a>\n' );
document.write( '                                    <a href=\"pjs/sidenav.html\" class=\"nav-item\"><span>Sidenav</span></a>\n' );
document.write( '                                    <a href=\"pjs/tabs.html\" class=\"nav-item\"><span>Tabs</span></a>\n' );
document.write( '                                    <a href=\"pjs/toasts.html\" class=\"nav-item\"><span>Toasts</span></a>\n' );
document.write( '                                    <a href=\"pjs/tooltips.html\" class=\"nav-item\"><span>Tooltips</span></a>\n' );
document.write( '                                    <a href=\"pjs/btn-active-animation.html\" class=\"nav-item\"><span>BTN Active Animation</span></a>\n' );
document.write( '                                </div>\n' );
document.write( '                                <div class=\"nav-item collapsible-opener\" sw=\"#form\"><span>Form</span></div>\n' );
document.write( '                                <div id=\"form\" class=\"collapsible-list\">\n' );
document.write( '                                    <a href=\"form/dropdown.html\" class=\"nav-item\"><span>Dropdown</span></a>\n' );
document.write( '                                    <a href=\"form/shrinking-inputs.html\" class=\"nav-item\"><span>Shrinking Inputs</span></a>\n' );
document.write( '                                    <a href=\"form/checkbox.html\" class=\"nav-item\"><span>Checkbox</span></a>\n' );
document.write( '                                    <a href=\"form/tags.html\" class=\"nav-item\"><span>Tags</span></a>\n' );
document.write( '                                    <a href=\"form/datepicker.html\" class=\"nav-item\"><span>Datepicker</span></a>\n' );
document.write( '                                    <a href=\"form/radio.html\" class=\"nav-item\"><span>Radio</span></a>\n' );
document.write( '                                    <a href=\"form/range.html\" class=\"nav-item\"><span>Range</span></a>\n' );
document.write( '                                    <a href=\"form/select.html\" class=\"nav-item\"><span>Select</span></a>\n' );
document.write( '                                    <a href=\"form/switches.html\" class=\"nav-item\"><span>Switches</span></a>\n' );
document.write( '                                    <a href=\"form/uploader.html\" class=\"nav-item\"><span>Uploader</span></a>\n' );
document.write( '                                </div>\n' );
document.write( '                            </div>\n' );
document.write( '                        </div>\n' );
document.write( '                        <div class=\"nav-footer\"></div>\n' );
document.write( '                    </div>\n' );
document.write( '                </nav>' );
